version: '3'
services:
  mongo:
    container_name: MONGODB_MOODBOX
    image: 'mongo'
    ports:
      - '27017:27017'
  app:
    container_name: BACKEND_MOODBOX
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo  
  